$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
dictionaryDefinitions:
  - name: dictionary
    path: "./dictionary.txt"
    addWords: true
dictionaries:
  - dictionary
ignorePaths:
  - "cspell.config.yaml"
  - "**/coverage/**"
  - "dictionary.txt"
  - "**/Dockerfile"
  - ".vscode"
  - "**.svg"
  - "**/package.json"
  - "**/package-lock.json"
  - "**/node_modules"
  - "**/__e2e__"
  - "**/__test__"
