packages:
  - "duardo"
  - "octavio"
  - "packages/zenn-editor/packages/zenn-content-css"
  - "packages/zenn-editor/packages/zenn-embed-elements"
  - "packages/zenn-editor/packages/zenn-markdown-html"
