name: Backend CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: backend

jobs:
  connect:
    name: Connect Generation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: proto
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Connect Cache
        id: connect-cache
        uses: actions/cache@v2
        with:
          path: ./backend/internal/proto
          key: connect-${{ hashFiles('**/*.proto') }}
      - name: Setup Go
        if: steps.connect-cache.outputs.cache-hit != 'true'
        uses: actions/setup-go@v4
        with:
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum
      - name: Install buf
        if: steps.connect-cache.outputs.cache-hit != 'true'
        uses: bufbuild/buf-setup-action@v1
      - name: Install Connect Related Packages
        if: steps.connect-cache.outputs.cache-hit != 'true'
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install connectrpc.com/connect/cmd/protoc-gen-connect-go@latest
      - name: Generate Connect Files
        if: steps.connect-cache.outputs.cache-hit != 'true'
        run: buf generate
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: connect
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Connect Cache
        id: connect-cache
        uses: actions/cache@v2
        with:
          path: ./backend/internal/proto
          key: connect-${{ hashFiles('**/*.proto') }}
      - name: Run golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          go_version_file: backend/go.mod
          workdir: backend
          fail_on_error: true
          filter_mode: nofilter
          golangci_lint_flags: --timeout=10m
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: connect
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum
      - name: Set Connect Cache
        id: connect-cache
        uses: actions/cache@v2
        with:
          path: ./backend/internal/proto
          key: connect-${{ hashFiles('**/*.proto') }}
      - name: Mod Download
        run: go mod download
      - name: Build
        run: go build
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Connect Cache
        id: connect-cache
        uses: actions/cache@v2
        with:
          path: ./backend/internal/proto
          key: connect-${{ hashFiles('**/*.proto') }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum
      - name: Run Test
        run: go test ./... -v
