name: Protobuf CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run buf-lint
        uses: bufbuild/buf-lint-action@v1
        with:
          input: proto
  breaking:
    name: Check Breaking Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run buf-breaking
        uses: bufbuild/buf-breaking-action@v1
        with:
          input: proto
          against: .git#branch=main
