name: Protobuf CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: proto

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Buff
        uses: bufbuild/buf-setup-action@v1
      - name: Run buf lint
        uses: bufbuild/buf-lint-action@v1
